### ISSUE TITLE
[FE] Make skeletons of all screens in Login epic

### ISSUE THREAD

**Issue by adil1508** [aarajh/draftt#35]
This is barebones screens. Think HTML webpages.

The 3 screens we need for now are:

- Splash screen
- Login 
- Signup
- Default Home screen

**Comment by adil1508** [comment]
This is will be closed when signup screen is merged

**Comment by aarajh** [comment]
Forgot Password screen still pending

**Comment by adil1508** [comment]
Oh yes. will create card for that and block this
